server:
  port: 9609
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
webapp:
  title: 大数据管理平台
management:
   endpoint:
     beans:
       enabled: true
     web:
       exposure:
         include:*
     shutdown:
       enabled: true
mqtt:
  username: eam
  password: Eam#2020
  host: tcp://132.232.111.110:1883
  clientinid: eamwj
  topic: /init
  timeout: 10000
  keepalibe: 20

  # host: tcp://47.97.65.233:18083


mqttTest:
  username: eam
  password: Eam#2020
  host: tcp://132.232.111.110:1883
  clientinid: eamwj_test
  topic: /init
  timeout: 10000
  keepalibe: 20

fileDirPath: C://eam//images//
thumbnailBoundsSize: 200
thumbnailFileSize : 10

durid:
  username: admin
  password: admin